### PR TITLE
Fixes to work with C++ standards newer than 98, add CI

### PR DESCRIPTION
**Pull request by wxmerkt**

### CODE REVIEW

**Comment by awesomebytes** [comment]
Hey @wxmerkt thanks a lot for this PR!

@wew84  or @Noam-Dori should review this PR, as I'm quite disconnected with it.

I would also like to note that this repo comes from a time where ddynamic_reconfigure was not in a state to be shared publicly and PAL gave me permission to publish a stripped fork to work as a community to make it open source. Meanwhile, PAL has released their version: https://github.com/pal-robotics/ddynamic_reconfigure
Maybe you are using this one and PAL's official one is just too different for you, but I thought I'd point it out, just in case.

**Comment by wxmerkt** [comment]
Hey @awesomebytes 
Many thanks for the note - I will have to take a look at possibly switching to PAL's now released official version if the packages that required this fork have been updated or are easy to change (I had this package in an underlay workspace for a long time and it stopped building recently, hence the fixes). If the modifications aren't useful, please close the PR

**Comment by awesomebytes** [comment]
The modifications look great! However, I'm not currently using this project, so I would like at least one of the collaborators that were working on it to chip in before I blindly merge this without looking into it close enough.
If you take a look at PAL's official release and notice something different that would stop you from migrating I think it would be beneficial for anyone that uses this project if you also left a comment here. Again, thanks for the effort, very appreciated.

**Comment by Noam-Dori** [comment]
I went over the modifications, they don't appear to break anything unexpected, and the changes made are welcomed.
I didn't really work with CI with the existing test, rather I ran the tests manually, so I can't really comment for or against this.

@awesomebytes you can merge the branch if you see no issue.

**Comment by awesomebytes** [comment]
Thanks @Noam-Dori ! I agree with you and I will proceed to merge. I also will listen to the other PR: https://github.com/awesomebytes/ddynamic_reconfigure/pull/8 and add a notice that users may want to use PAL's released version instead.

**Pull request merged**
